language: csharp
solution: MyGame.sln
install:
  - nuget restore MyGame.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release MyGame.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./TestsMono/bin/Debug/TestMono.dll
