language: csharp
solution: ./ducksteroid/MyGame.sln
matrix:
  include:
    - dotnet: 2.1
      mono: none
      script:
        - sudo apt-get install dotnet-sdk-2.1
        - export FrameworkPathOverride=/usr/lib/mono/4.0/
        - dotnet restore ./ducksteroid/MyGame.csproj
        - dotnet build ./ducksteroid/MyGame.sln
        - cp ./ducksteroid/bin/Debug/mscorlib.dll ./Tests/bin/Debug/netcoreapp2.1/mscorlib.dll
        - cp ./ducksteroid/bin/Debug/SGSDK.dll ./Tests/bin/Debug/netcoreapp2.1/SGSDK.dll
        - cp ./ducksteroid/bin/Debug/libSGSDK.dylib ./Tests/bin/Debug/netcoreapp2.1/libSGSDK.dylib
      after_script:
        - dotnet test ./Tests/Tests.csproj --no-build
    - mono: latest
      install:
        - nuget restore ./ducksteroid/MyGame.sln
        - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
      script:
        - msbuild /p:Configuration=Release ./ducksteroid/MyGame.sln
        - cp ./ducksteroid/bin/Debug/SGSDK.dll ./ducksteroid/TestsMono/bin/Debug/SGSDK.dll
        - cp ./ducksteroid/bin/Debug/libSGSDK.dylib ./ducksteroid/TestsMono/bin/Debug/libSGSDK.dylib
      after_script:
        - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./ducksteroid/TestsMono/bin/Debug/TestsMono.dll
