language: csharp
solution: ./ducksteroid/MyGame.sln
matrix:
  include:
    - dotnet: 2.1
      mono: none
      script:
        - cd /usr/lib/mono
        - cp -R ./4.0 /home/travis/build/dannamachi/ducksteroid/framework
        - cd /home/travis/build/dannamachi/ducksteroid
        - export FrameworkPathOverride=/home/travis/build/dannamachi/ducksteroid/framework/
        - cp ./ducksteroid/mscorlib.dll ./framework/mscorlib.dll
        - dotnet restore ./ducksteroid/MyGame.csproj
        - dotnet build ./ducksteroid/MyGame.sln
    - mono: latest
      install:
        - nuget restore ./ducksteroid/MyGame.sln
        - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
      script:
        - msbuild /p:Configuration=Release ./ducksteroid/MyGame.sln
        - cp ./ducksteroid/bin/Debug/SGSDK.dll ./ducksteroid/TestsMono/bin/Debug/SGSDK.dll
        - cp ./ducksteroid/bin/Debug/libSGSDK.dylib ./ducksteroid/TestsMono/bin/Debug/libSGSDK.dylib
      after_script:
        - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./ducksteroid/TestsMono/bin/Debug/TestsMono.dll
